application:
  subdomain: avcnv
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://avcnv:5123/

services:
  avcnv:
    # upstream: docker.io/evilhsu/avcnv:latest
    image: docker.1ms.run/evilhsu/avcnv:latest
    environment:
      - LOG_LEVEL=INFO
    binds:
      - /lzcapp/var/uploads:/app/uploads
      - /lzcapp/var/localfiles:/app/localfiles
      - /lzcapp/var/outputs:/app/outputs
